SELECT DISTINCT
       "D_BU"."BU_CODE" AS "BU Code",
       "D_GLOBAL_HIERARCHY"."GLOBAL_HIERARCHY_DESC1" AS "Global Hierarchy Desc1",
       "D_GLOBAL_HIERARCHY"."GLOBAL_HIERARCHY_DESC2" AS "Global Hierarchy Desc2",
       "D_GLOBAL_HIERARCHY"."GLOBAL_HIERARCHY_DESC3" AS "Global Hierarchy Desc3",
       "D_GLOBAL_HIERARCHY"."GLOBAL_HIERARCHY_DESC4" AS "Global Hierarchy Desc4",
       "D_GLOBAL_HIERARCHY"."GLOBAL_HIERARCHY_CODE1" AS "Global Hierarchy Code1",
       "D_GLOBAL_HIERARCHY"."GLOBAL_HIERARCHY_CODE2" AS "Global Hierarchy Code2",
       "D_GLOBAL_HIERARCHY"."GLOBAL_HIERARCHY_CODE3" AS "Global Hierarchy Code3",
       "D_GLOBAL_HIERARCHY"."GLOBAL_HIERARCHY_CODE4" AS "Global Hierarchy Code4",
       "D_LOCAL_HIERARCHY"."LOCAL_HIERARCHY_DESC1" AS "Local Hierarchy Desc1",
       "D_LOCAL_HIERARCHY"."LOCAL_HIERARCHY_DESC2" AS "Local Hierarchy Desc2",
       "D_LOCAL_HIERARCHY"."LOCAL_HIERARCHY_DESC3" AS "Local Hierarchy Desc3",
       "D_LOCAL_HIERARCHY"."LOCAL_HIERARCHY_DESC4" AS "Local Hierarchy Desc4",
       "D_LOCAL_HIERARCHY"."LOCAL_HIERARCHY_CODE1" AS "Local Hierarchy Code1",
       "D_LOCAL_HIERARCHY"."LOCAL_HIERARCHY_CODE2" AS "Local Hierarchy Code2",
       "D_LOCAL_HIERARCHY"."LOCAL_HIERARCHY_CODE3" AS "Local Hierarchy Code3",
       "D_LOCAL_HIERARCHY"."LOCAL_HIERARCHY_CODE4" AS "Local Hierarchy Code4"    

FROM
       IBBI_STAGING."D_BU",
       IBBI_STAGING."D_GLOBAL_HIERARCHY",
       IBBI_STAGING."D_LOCAL_HIERARCHY",
       IBBI_STAGING."D_TIME_MONTH",
       IBBI_STAGING."D_ITEM_STS",
       IBBI_STAGING.D_ITEM

WHERE
       ( "D_GLOBAL_HIERARCHY"."GLOBAL_HIERARCHY_KEY"="D_LOCAL_HIERARCHY"."GLOBAL_HIERARCHY_KEY"  )
       AND  ( D_ITEM.LOCAL_HIERARCHY_ID="D_LOCAL_HIERARCHY"."LOCAL_HIERARCHY_ID"  )
       AND  ( D_ITEM.ITEM_ID = "D_ITEM_STS"."ITEM_ID"  AND  D_ITEM.BU_ID = "D_ITEM_STS"."BU_ID"  )
       AND  ( "D_TIME_MONTH"."TIME_MONTH_ID"="D_ITEM_STS"."TIME_MONTH_ID"  )
       AND  ( "D_BU"."BU_ID"="D_LOCAL_HIERARCHY"."BU_ID"  )
       AND  
       "D_TIME_MONTH"."FIS_YR"  IN  (2021, 2020, 2019, 2018)

