SELECT * FROM
(
	SELECT 
		"BU Code",
		"BU Brand Name",
		PRODUCT_DESC_ENG,
		PRODUCT_DESC_OTHERS,
		PRODUCT_CODE,
		ROW_NUMBER() OVER (PARTITION BY
			"BU Code",
			"BU Brand Name"
			ORDER BY
			"BU Code",
			"BU Brand Name") AS "rownum"
			
	FROM
		(SELECT DISTINCT
			"D_BU"."BU_CODE" AS "BU Code",
			"D_BU_BRAND"."BU_BRAND_NAME" AS "BU Brand Name",
			D_ITEM.PRODUCT_DESC_ENG,
			D_ITEM.PRODUCT_DESC_OTHERS,
			D_ITEM.PRODUCT_CODE
				
		FROM
			IBBI_STAGING."D_BU",
			IBBI_STAGING."D_BU_BRAND",
			IBBI_STAGING.D_ITEM,
			IBBI_STAGING."D_TIME_MONTH",
			IBBI_STAGING."D_ITEM_STS" SAMPLE(10) 
		
		WHERE
			( D_ITEM.ITEM_ID = "D_ITEM_STS"."ITEM_ID"  AND  D_ITEM.BU_ID = "D_ITEM_STS"."BU_ID"  )
			AND  ( "D_TIME_MONTH"."TIME_MONTH_ID"="D_ITEM_STS"."TIME_MONTH_ID"  )
			AND  "D_TIME_MONTH"."FIS_YR"  IN  ( 2021 )
			AND  "D_TIME_MONTH"."FIS_MON_NO" IN ( 7 )
			AND D_BU_BRAND."BU_BRAND_NAME" IN ( 'PERRIS MC ROSE DE TAIF' )
			AND D_BU."BU_CODE" IN ( 'ICINL')
		)
	)
WHERE "rownum" <= 5


	


