SELECT
  "D_BU"."BU_CODE",
  "D_GLOBAL_HIERARCHY"."GLOBAL_HIERARCHY_DESC1",
  "D_GLOBAL_HIERARCHY"."GLOBAL_HIERARCHY_DESC2",
  "D_GLOBAL_HIERARCHY"."GLOBAL_HIERARCHY_DESC3",
  "D_GLOBAL_HIERARCHY"."GLOBAL_HIERARCHY_DESC4",
  "D_GLOBAL_HIERARCHY"."GLOBAL_HIERARCHY_CODE1",
  "D_GLOBAL_HIERARCHY"."GLOBAL_HIERARCHY_CODE2",
  "D_GLOBAL_HIERARCHY"."GLOBAL_HIERARCHY_CODE3",
  "D_GLOBAL_HIERARCHY"."GLOBAL_HIERARCHY_CODE4",
  "D_LOCAL_HIERARCHY"."LOCAL_HIERARCHY_DESC1",
  "D_LOCAL_HIERARCHY"."LOCAL_HIERARCHY_DESC2",
  "D_LOCAL_HIERARCHY"."LOCAL_HIERARCHY_DESC3",
  "D_LOCAL_HIERARCHY"."LOCAL_HIERARCHY_DESC4",
  "D_LOCAL_HIERARCHY"."LOCAL_HIERARCHY_CODE1",
  "D_LOCAL_HIERARCHY"."LOCAL_HIERARCHY_CODE2",
  "D_LOCAL_HIERARCHY"."LOCAL_HIERARCHY_CODE3",
  "D_LOCAL_HIERARCHY"."LOCAL_HIERARCHY_CODE4"
FROM
  IBBI_STAGING."D_BU",
  IBBI_STAGING."D_GLOBAL_HIERARCHY",
  IBBI_STAGING."D_LOCAL_HIERARCHY",
  IBBI_STAGING."D_TIME_MONTH",
  IBBI_STAGING."D_ITEM_STS",
  IBBI_STAGING.D_ITEM
WHERE
  ( "D_GLOBAL_HIERARCHY"."GLOBAL_HIERARCHY_KEY"="D_LOCAL_HIERARCHY"."GLOBAL_HIERARCHY_KEY"  )
  AND  ( D_ITEM.LOCAL_HIERARCHY_ID="D_LOCAL_HIERARCHY"."LOCAL_HIERARCHY_ID"  )
  AND  ( D_ITEM.ITEM_ID = "D_ITEM_STS"."ITEM_ID"  AND  D_ITEM.BU_ID = "D_ITEM_STS"."BU_ID"  )
  AND  ( "D_TIME_MONTH"."TIME_MONTH_ID"="D_ITEM_STS"."TIME_MONTH_ID"  )
  AND  ( "D_BU"."BU_ID"="D_LOCAL_HIERARCHY"."BU_ID"  )
  AND  
  "D_TIME_MONTH"."FIS_YR_MON"  IN  ( '2021 - 06'  )


